#!/usr/bin/env python3
"""
FormulaFix Debug Report Analyzer.

Parses diagnostic zip files generated by ExportPipeline and prints
a human-readable summary of the observability data.

Usage:
    python tools/ffx-analyze/analyze.py <path-to-diagnostic-zip>
    python tools/ffx-analyze/analyze.py <path-to-extracted-directory>

Phase 3.7.3: 真机调试模式 + Export Pipeline
"""

import json
import os
import sys
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path


def main():
    if len(sys.argv) < 2:
        print("Usage: python analyze.py <path-to-diagnostic-zip>")
        sys.exit(1)

    path = sys.argv[1]
    if not os.path.exists(path):
        print(f"Error: path not found: {path}")
        sys.exit(1)

    # Determine if input is a zip or already extracted directory
    if path.endswith(".zip"):
        work_dir = tempfile.mkdtemp(prefix="ffx_analyze_")
        try:
            with zipfile.ZipFile(path, "r") as zf:
                zf.extractall(work_dir)
            _analyze_dir(work_dir)
        finally:
            import shutil
            shutil.rmtree(work_dir, ignore_errors=True)
    elif os.path.isdir(path):
        _analyze_dir(path)
    else:
        print(f"Error: unsupported path type: {path}")
        sys.exit(1)


def _analyze_dir(dir_path: str):
    """Analyze an extracted diagnostic directory."""
    metadata = _load_json(dir_path, "metadata.json")
    trace = _load_json(dir_path, "trace.json")
    snapshot = _load_json(dir_path, "snapshot.json")
    invariant = _load_json(dir_path, "invariant_report.json")

    print("=" * 60)
    print("  FormulaFix Debug Report Analyzer")
    print("=" * 60)
    print()

    # ============ Metadata ============
    _print_section("Metadata")
    if metadata:
        _print_kv("Version", metadata.get("version", "N/A"))
        _print_kv("Time", metadata.get("time", "N/A"))
        _print_kv("Session ID", metadata.get("sessionId", "N/A"))
        _print_kv("Level", metadata.get("observabilityLevel", "N/A"))
        _print_kv("Commands", metadata.get("commandCount", 0))
        _print_kv("Transactions", metadata.get("transactionCount", 0))
        _print_kv("Interactions", metadata.get("interactionCount", 0))
        _print_kv("Renders", metadata.get("renderCount", 0))
    else:
        print("  (not found)")
    print()

    # ============ Trace ============
    _print_section("Trace Events")
    if trace:
        interactions = trace.get("interactions", [])
        commands = trace.get("commands", [])
        transactions = trace.get("transactions", [])
        renders = trace.get("renders", [])

        print(f"  Interactions: {len(interactions)}")
        print(f"  Commands:     {len(commands)}")
        print(f"  Transactions: {len(transactions)}")
        print(f"  Renders:      {len(renders)}")
        print()

        if interactions:
            print("  --- Recent Interactions (last 10) ---")
            for event in interactions[-10:]:
                _print_interaction(event)
            print()

        if commands:
            print("  --- Recent Commands (last 10) ---")
            for cmd in commands[-10:]:
                _print_command(cmd)
            print()

        if transactions:
            failed = [t for t in transactions if t.get("result") == "rollback"]
            if failed:
                print(f"  --- Rolled Back Transactions ({len(failed)}) ---")
                for t in failed:
                    _print_transaction(t)
                print()

        if renders:
            print("  --- Recent Render Events (last 10) ---")
            for event in renders[-10:]:
                _print_render(event)
            print()

            anomalies = _find_render_anomalies(renders)
            if anomalies:
                print(f"  ⚠ Render Anomalies ({len(anomalies)}) ---")
                for a in anomalies:
                    _print_render(a)
                print()
    else:
        print("  (not found)")
        print()

    # ============ Error Snapshot ============
    _print_section("Error Snapshot")
    if snapshot:
        snap_type = snapshot.get("type", "N/A")
        snap_msg = snapshot.get("message", "N/A")
        snap_time = snapshot.get("timestamp", "N/A")
        snap_mode = snapshot.get("snapshotMode", "N/A")

        print(f"  Type:      {snap_type}")
        print(f"  Message:   {snap_msg}")
        print(f"  Time:      {snap_time}")
        print(f"  Mode:      {snap_mode}")

        cmd = snapshot.get("command")
        if cmd:
            print(f"  Command:   {cmd.get('name', 'N/A')}")
            params = cmd.get("params", {})
            if params:
                print(f"  Params:    {json.dumps(params, ensure_ascii=False)}")

        cursor = snapshot.get("cursor")
        if cursor:
            print(f"  Cursor:    block={cursor.get('blockId', 'N/A')}, "
                  f"offset={cursor.get('offset', 'N/A')}")

        recent = snapshot.get("recentCommands", [])
        if recent:
            print(f"  Recent Ops: {len(recent)}")
            for op in recent[-5:]:
                print(f"    - {op.get('name', 'N/A')} "
                      f"({'OK' if op.get('succeeded', False) else 'FAIL'})")

        env = snapshot.get("environment", {})
        if env:
            print(f"  App:       {env.get('appVersion', 'N/A')}")
            print(f"  Platform:  {env.get('platform', 'N/A')}")
    else:
        print("  (no error snapshot recorded)")
    print()

    # ============ Invariant Report ============
    _print_section("Invariant Report")
    if invariant:
        print(f"  Last Check: {invariant.get('lastCheckTime', 'N/A')}")
        print(f"  Result:     {invariant.get('result', 'N/A')}")
        print(f"  Invariants: {', '.join(invariant.get('invariants', []))}")
    else:
        print("  (not checked)")
    print()

    # ============ README ============
    readme_path = os.path.join(dir_path, "README.txt")
    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            content = f.read().strip()
        _print_section("README.txt")
        print(f"  {content[:200]}...")
        print()

    print("=" * 60)


def _load_json(dir_path: str, filename: str):
    """Load a JSON file from directory, return None if not found."""
    path = os.path.join(dir_path, filename)
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"  Warning: failed to parse {filename}: {e}")
        return None


def _print_section(title: str):
    """Print a section header."""
    print(f"  [{title}]")


def _print_kv(key: str, value):
    """Print a key-value pair."""
    print(f"  {key}: {value}")


def _print_interaction(event: dict):
    """Print a single interaction event."""
    etype = event.get("type", "?")
    ts = event.get("timestamp", "?")
    match etype:
        case "UserTap":
            print(f"    TAP   {event.get('target', '?')}  @ {ts}")
        case "UserInput":
            text = event.get("text", "")
            if len(text) > 40:
                text = text[:40] + "..."
            print(f"    INPUT \"{text}\"  @ {ts}")
        case "UserDelete":
            print(f"    DEL   {event.get('count', '?')} chars  @ {ts}")
        case "UserFormatToggle":
            print(f"    FMT   {event.get('format', '?')}  @ {ts}")
        case "UserUndoRedo":
            action = "UNDO" if event.get("isUndo") else "REDO"
            print(f"    {action}  @ {ts}")
        case _:
            print(f"    {etype}  @ {ts}")


def _print_command(cmd: dict):
    """Print a single command entry."""
    name = cmd.get("commandName", "?")
    ok = "OK" if cmd.get("succeeded", False) else "FAIL"
    ts = cmd.get("timestamp", "?")
    err = cmd.get("errorMessage", "")
    err_str = f" [{err}]" if err else ""
    print(f"    {name}  [{ok}]{err_str}  @ {ts}")


def _print_transaction(t: dict):
    """Print a single transaction entry."""
    tid = t.get("transactionId", "?")[:12]
    result = t.get("result", "?")
    reason = t.get("rollbackReason", "")
    reason_str = f"  reason={reason}" if reason else ""
    print(f"    TX {tid}  [{result}]{reason_str}")


def _print_render(event: dict):
    """Print a single render event."""
    etype = event.get("type", "?")
    ts = event.get("timestamp", "?")
    match etype:
        case "CodeBlockThemeRendered":
            is_dark = event.get("isDark", False)
            theme = event.get("themeName", "?")
            lang = event.get("language", "?")
            print(f"    THEME  dark={is_dark} theme={theme} lang={lang}  @ {ts}")
        case "CodeBlockLanguageChipRendered":
            lang = event.get("language")
            shown = event.get("shown", False)
            mode = event.get("mode", "?")
            print(f"    CHIP   lang={lang} shown={shown} mode={mode}  @ {ts}")
        case "PdfCjkFontFallbackEvent":
            loaded = event.get("fontLoaded", False)
            fallback = event.get("fallbackActive", False)
            has_cjk = event.get("hasCjk", False)
            lang = event.get("language")
            code_len = event.get("codeLength", 0)
            print(f"    PDFCJK loaded={loaded} fallback={fallback}"
                  f" hasCjk={has_cjk} lang={lang} codeLen={code_len}  @ {ts}")
        case _:
            print(f"    {etype}  @ {ts}")


def _find_render_anomalies(renders: list) -> list:
    """Find render events that indicate potential issues."""
    anomalies = []
    for event in renders:
        etype = event.get("type", "")
        match etype:
            case "PdfCjkFontFallbackEvent":
                if event.get("hasCjk") and not event.get("fallbackActive"):
                    anomalies.append(event)
            case "CodeBlockThemeRendered":
                is_dark = event.get("isDark", False)
                theme = event.get("themeName", "")
                if is_dark and theme != "atomOneDark":
                    anomalies.append(event)
                elif not is_dark and theme != "github":
                    anomalies.append(event)
            case "CodeBlockLanguageChipRendered":
                lang = event.get("language")
                shown = event.get("shown", False)
                has_lang = lang is not None and lang != ""
                if has_lang != shown:
                    anomalies.append(event)
    return anomalies


if __name__ == "__main__":
    main()